### ISSUE TITLE
Template parses rotate amounts as hex not decimal

### ISSUE THREAD

**Issue by ajohnson1** [skeeto/hash-prospector#2]
The other shift type operations parse the shift amount as decimal, so it would be more logical to parse rotates as decimal too.

`./prospector   -8   -t 10000  -p rot:32`

See these which might be better moved to the other set of switch cases.
https://github.com/skeeto/hash-prospector/blob/627f16cce31fa1e9377ea624765d4fca5eb518f4/prospector.c#L675
https://github.com/skeeto/hash-prospector/blob/627f16cce31fa1e9377ea624765d4fca5eb518f4/prospector.c#L679

**Comment by skeeto** [comment]
You're right, thanks! I think this was just an oversight on my part.
