### ISSUE TITLE
Are score of 32bit and 16bit hashes with the same unit?

### ISSUE THREAD

**Issue by gzm55** [skeeto/hash-prospector#9]
In `prospector.c` for searching 32/64 bits hashes, the scores are multiplied by [`1000.0`](https://github.com/skeeto/hash-prospector/blob/master/prospector.c#L605), while not in the [`hp16.c`](https://github.com/skeeto/hash-prospector/blob/master/hp16.c#L341).

Is it on purpose?

**Comment by skeeto** [comment]
I did that before to scale the value closer to 1 for convenience. The 
scores are already incomparable between categories (16-bit exact, 32-bit 
exact, 64-bit exact, 32-bit estimate, 64-bit estimate) and are only 
intended as a relative comparison between functions within a category. I 
just chose not to do it in hp16.c.
